name: fourmolu
on:
  - push
  - pull_request
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: haskell-actions/run-fourmolu@v13
        with:
          pattern: |
            src/**/*.hs
